regions:
  - ap-south-1
  - ap-southeast-1
  - global

blocklist:
  - "111122223333"

no-blocklist-terms-default: true

bypass-alias-check-accounts:
  - 271547278517

# resource-types:
#   excludes:
#     - IAMRole
#     - IAMRolePolicyAttachment
#     - IAMOpenIDConnectProvider

resource-types:
  includes:
    - S3Object
    - S3Bucket
    - EC2DHCPOption
    - CloudWatchEventsTarget
    - SNSSubscription

accounts:
  "271547278517":
    filters:
      IAMOpenIDConnectProvider:
        - "arn:aws:iam::*:oidc-provider/token.actions.githubusercontent.com"
      IAMRole:
        - "actions"
      IAMRolePolicyAttachment:
        - "actions -> *"