regions:
- eu-west-1

blocklist:
  - "111122223333"

no-blocklist-terms-default: true

bypass-alias-check-accounts:
  - 271547278517

resource-types:
  excludes:
    - IAMUser
    - IAMUserAccessKey
    - IAMUserPolicyAttachment
  includes:
    - S3Object
    - S3Bucket
    - EC2Instance
  

accounts:
  "271547278517":
    filters:
      IAMUser:
      - "raghavendra.merugu@neonxt.com"
      IAMUserPolicyAttachment:
      - "raghavendra.merugu@neonxt.com -> AdministratorAccess"
      IAMUserAccessKey:
      - "raghavendra.merugu@neonxt.com -> AKIAT6OL2US24JK24WXY"