name: Multi Context Workflow
on: 
  push:
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Cache Dependencies
        uses: actions/cache@v4
        id: caching
        with:
          path: node_modules
          key: ${{ runner.os }}-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: ${{ steps.caching.outputs.cache-hit }} != 'true'
        run: npm ci
      - name: Lint Code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Cache Dependencies
        uses: actions/cache@v4
        id: caching
        with:
          path: node_modules
          key: ${{ runner.os }}-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: ${{ steps.caching.outputs.cache-hit }} != 'true'
        run: npm ci
      - name: Test Code
        id: test-case
        run: npm run test
      - name: Upload Test report
        if: failure() && ${{ steps.test-case.outcome }} != 'success'
        uses: actions/upload-artifact@v4
        with: 
          name: test-report
          path: testing.json

  build: 
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Cache Dependencies
        uses: actions/cache@v4
        id: caching
        with:
          path: node_modules
          key: ${{ runner.os }}-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: ${{ steps.caching.outputs.cache-hit }} != 'true'
        run: npm ci
      - name: Build Code
        run: npm run build
      - name: Upload Dist Files
        uses: actions/upload-artifact@v4
        with:  
          name: dist-files
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with: 
          name: dist-files
      - name: Output Files
        run: ls
      - name: Deploying Application
        run: echo "Deployed & Uploaded"
    
  report: 
    runs-on: ubuntu-latest
    needs: [lint, deploy]
    if: failure()
    steps: 
      - name: Failure
        run: "Something went wrong, one of the job failed"
      - name: Output GitHub Context
        run: echo "${{ toJSON(github) }}"