name: Matrix Workflow
on:
  push:
    paths:
      - .github/workflows/matrix.yml
  workflow_dispatch:

jobs:
  matrix-job:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [18, 20, 24]
        include:  
          - os: ubuntu-latest  # This combo will be added to the existing matrix
            node-version: 24
        exlude: 
          - os: macos-latest   # This combo will be removed from the existing matrix
            node-version: 20
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup NodeJS
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - name: Deploying application
        run: echo "Deployed application...."