name: Workflow Call
on: 
  workflow_call:
    inputs: 
      artifact-name:
        required: false
        description: 'Name of the artifact to download'
        default: dist-files
        type: string
    secrets:
      some-secret:
        required: false
        description: 'A secret for deployment'
    outputs:
      result:
        description: 'Deployment status'
        value: ${{ jobs.reusable-workflow.outputs.status}}
jobs:
  reusable-workflow:
    outputs:
      status: ${{ steps.set-output.outputs.deployment-status }}
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with: 
          name: ${{ inputs.artifact-name }}
      - name: Output Files
        run: ls
      - name: Deploying Application
        run: | 
          echo "Deployed & Uploaded"
          echo "Output Variable = ${{ vars.ENV }}"
      - name: Output GitHub Context
        run: echo "${{ toJSON(github) }}"
      - name: Set Output
        id: set-output
        run: echo "deployment-status=success" >> $GITHUB_OUTPUT