name: Workflow Call
on: 
  workflow_call:
    inputs: 
      artifact-name:
        required: true
        description: 'Name of the artifact to download'
        default: dist
        type: string
jobs:
  reusable-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with: 
          name: ${{ inputs.artifact-name }}
      - name: Output Files
        run: ls
      - name: Deploying Application
        run: echo "Deployed & Uploaded"
      - name: Output GitHub Context
        run: echo "${{ toJSON(github) }}"