name: Workflow Call
on: workflow_call
jobs:
  reusable-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with: 
          name: dist-files
      - name: Output Files
        run: ls
      - name: Deploying Application
        run: echo "Deployed & Uploaded"
      - name: Output GitHub Context
        run: echo "${{ toJSON(github) }}"